# Generated by Django 3.0.5 on 2020-11-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201121_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
    ]
