# Generated by Django 3.0.5 on 2020-11-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201116_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='landmark',
        ),
    ]
